---
# tasks file for code

- name: create user
  user:
    name: "{{ app_user }}"

- name: Creates directory
  file:
    path: "{{ app_folder }}"
    state: directory
    owner: "{{ app_user }}"
    mode: 0755
    recurse: yes

- name: untar repo source code
  unarchive:
    src: "{{ archived_code }}"
    dest: "{{ app_folder }}"
    remote_src: yes
    owner: "{{ app_user }}"
<<<<<<< HEAD

- name: Set permissions for files
  cmd: "find {{ app_folder }} -type f -exec chmod 644 {} \\;"

- name: Set permissions for folders
  cmd: "find {{ app_folder }} -type d -exec chmod 755 {} \\;"
=======
    mode: 0644
>>>>>>> 0750711... Update main.yml
