---
# tasks file for code

- name: create user
  user:
    name: "{{ app_user }}"
    shell: "{{ user_shell | default('/bin/bash') }}"

- name: Creates directory
  file:
    path: "{{ app_folder }}"
    state: directory
    owner: "{{ app_user }}"
    mode: 0755
    recurse: yes

- name: untar repo source code
  unarchive:
    src: "{{ archived_code }}"
    dest: "{{ app_folder }}"
    remote_src: yes
    owner: "{{ app_user }}"

- name: Set permissions for files
  command: "find {{ app_folder }} -type f -exec chmod 644 {} \\;"

- name: Set permissions for folders
  command: "find {{ app_folder }} -type d -exec chmod 755 {} \\;"
